initial_pos:

  # TODO port from TA's example

  # self.x_RH0, self.y_RH0, self.z_RH0, self.x_LH0, self.y_LH0, self.z_LH0 = 0.0, -174.00, -12.00, 0.0, 174.0, -12.0
        self.x_RF0, self.y_RF0, self.z_RF0, self.roll_RF0, self.pitch_RF0 = 15.0, -33.0, -196.0, 0.0, 0.0
        self.x_LF0, self.y_LF0, self.z_LF0, self.roll_LF0, self.pitch_LF0 = 15.0, 33.0, -196.0, 0.0, 0.0

    initial_positions: [
      0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
    ]
